from execution.runtime_dependency import RuntimeDependency


def test_runtime_dependency_contract():
    dependency = RuntimeDependency(
        consumer_testcase_id="TC-CUST-011",
        variable_name="customerId",
        producer_testcase_id="TC-CUST-008",
        source="create_response.customerId",
        required=True,
        description="Customer ID generated by successful customer creation",
    )

    assert dependency.validate() is True
    assert dependency.consumer_testcase_id == "TC-CUST-011"
    assert dependency.variable_name == "customerId"
    assert dependency.producer_testcase_id == "TC-CUST-008"
    assert dependency.source == "create_response.customerId"


def test_runtime_dependency_rejects_missing_producer():
    dependency = RuntimeDependency(
        consumer_testcase_id="TC-CUST-011",
        variable_name="customerId",
        producer_testcase_id="",
        source="create_response.customerId",
    )

    try:
        dependency.validate()
        assert False, "Expected ValueError"
    except ValueError as exc:
        assert "producer_testcase_id" in str(exc)